### PR TITLE
CONTRAST-21265 Chrome Plugin should confirm configuration before actu…

### PR DESCRIPTION
**Pull request by serge17**
When the chrome plugin detects that the user is on the "your account" page, we should show a popup asking the user if they want to configure their chrome plugin?

### CODE REVIEW

**Comment by gmoore** [comment]
Is there any way to add more text to this thing or make it bigger? 

screen shot 2018-03-06 at 10 30 41 am

If not we may need to find an alternative.

How does it look on Windows?

**Comment by serge17** [comment]
@gmoore I removed the notification title to make more space. Can you try again please.
Do you have the "Configure" button?

untitled

**Comment by gmoore** [comment]
Yeah it's still a mess on OSX. Is there was a way to "pop-up" the extension window instead of using the native notifications?

**Comment by serge17** [comment]
@gmoore Now the dialog suggesting to configure the plugin is shown inside the plugin popup. The extension icon has a red dot on the account page.

untitled

**Comment by gmoore** [comment]
This looks good! 

1) Make the little badge yellow.

2)Add this text on a new line between what is already there and the button:

"Make sure you trust this site: (hostname of the site they're on)"

3) Unfortunately, the extension is now behaving differently. The badge counts are not showing up, and clicking on the extension does this little dance before it gets the vulns.


extension-jitter

TO be clear: two problems. Badge counts not showing up. Jitter when loading vulns.

**Comment by serge17** [comment]
@gmoore Should be fixed now, but the extension popup window will change in size when opened. The reason is that it decides which view to show based on the vulnerabilities on the page.

**Comment by gmoore** [comment]
The little badge didn't popup on the Your Account page.

screen shot 2018-03-16 at 6 10 04 pm

**Pull request merged**
