### PR TITLE
Implement user interface

### PR DESCRIPTION
**Pull request by serge17**
Make the Chrome extension window not as tall
Delete the activity feed and all views/js that go with it
The chrome extension will now have three views: Sign in button (and the settings page), vulnerability found on this page, no vulnerability found on this page
Change styling

### CODE REVIEW

**Comment by gmoore** [comment]
This looks so much better 🎲 

0) What app are you using for testing this?

1) There's a merge conflict coming after I merged the other PR. Pull master back into this branch and resolve the merge.

2) There's a weird blue outline on the setting gear icon. Not sure why.

screen shot 2018-02-21 at 9 16 50 am

3) Go a little lighter on the email address font color. #999 ? #666 ?

4) Top C logo a little smaller and bring the "Contrast" and "Discovered Vulnerabilities" closer together and closer to the logo

screen shot 2018-02-21 at 9 28 04 am

5) When there is a vulnerability, the image NOTE looks a little blurry. Are we stretching it too big? I assume this applies to the others (CRITICAL, etc..)

6) The vulnerability list is drifting off by itself. Move it up and to the left a bit.

screen shot 2018-02-21 at 9 32 45 am

7) Can you show me a screenshot with three vulnerabilities? Also one with 20 vulnerabilities. Pack them in manually in the code if you need to.

**Comment by serge17** [comment]
@gmoore I used railsgoat for testing. I did not apply any styles to severity images, so they should look normal. 
Everything is done except for the blue outline. It does not appear on ubuntu or windows. Can you check please if there is a CSS border property?

**Comment by gmoore** [comment]
Closer!

1) Apply these styles to the "we're not configured yet screen" Obviously we won't be showing the vulnerabilities (because we're not configured)

2) Bring "Contrast" and "Discovered Vulnerabilities" a little closer together.

3) "Contrast" and "Discovered Vulnerabilities" isn't the right font. It should be either Roboto or Lato. If neither of those look right we can nag the UX team.

4) In the mock ups it looks like the items on the vulnerability list are a little closer together.

**Comment by serge17** [comment]
@gmoore Everything is resolved

**Comment by gmoore** [comment]
Nice work 🏆

**Pull request merged**
